# RabbitMQ container with web_stomp and federation plugins

from dockerfile/rabbitmq

MAINTAINER Sylvain Boily "sboily@avencall.com"

RUN rabbitmq-plugins enable --offline rabbitmq_web_stomp rabbitmq_federation

EXPOSE 15674
